
export const Material = {
    add_circle_outline: '\ue3ba',
    add: '\ue145',
    apps: '\ue5c3',
    arrow_drop_down: '\ue5c5',
    circle_add: '\ue3ba',
    circle_play: '\ue039',
    close: '\ue14c',
    default_order: '\ue16d',
    disc: '\ue39e',
    edit: '\ue254',
    event: '\ue8df',
    gear: '\ue8b8',
    heart_empty: '\ue87e',
    heart: '\ue87d',
    history: '\ue8b3',
    menu: '\ue5d2',
    more_horiz: '\ue5d3',
    more_vert: '\ue5d4',
    music_note: '\ue3a1',
    pause: '\ue034',
    play_arrow: '\ue037',
    play: '\ue037',
    queue_music: '\ue03d',
    repeat: '\ue040',
    repeat1: '\ue041',
    search: '\ue8b6',
    settings: '\ue8b8',
    shuffle: '\ue043',
    skip_next: '\ue044',
    skip_prev: '\ue045',
    sort: '\ue0c3',
    star_border: '\ue83a',
    volume_mute: '\ue04e',
    volume_off: '\ue04f',
    volume: '\ue050',
    time: '\ue192',
    arrow_right: '\ue5c8',
    star: '\ue838',
    star_empty: '\ue83a',
    favorite_border: '\ue87e',
    library: '\ue030',
    playlist_play: '\ue05f',
    queue: '\ue02e',
    playlist_add: '\ue03b',
    never_played: '\ue426',
    newly_added: '\ue3bb',
    toggle_dark: '\ue3aB',
    navigate_previous: '\ue314',
    navigate_next: '\ue315',
};

export const MaterialFont = "Material Icons";
